name: Nix Flake Check
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  check:
    strategy:
      matrix:
        runner: [ubuntu-latest, ubuntu-24.04-arm]
    runs-on: ${{ matrix.runner }}
    steps:
      - uses: actions/checkout@v6
      - uses: DeterminateSystems/determinate-nix-action@v3
      - uses: DeterminateSystems/flake-checker-action@v12
      - run: nix flake check -L
